### ISSUE TITLE
The translation workflow (draft)

### ISSUE THREAD

**Issue by greyli** [flaskcwg/meta#1]
Update:

Now the translation workflow is based on Sphinx and gettext, see the [translation template repo](https://github.com/flaskcwg/translation-template), and [the instruction for language coordinator](https://github.com/flaskcwg/translation-coordination/blob/main/.github/ISSUE_TEMPLATE/new-translation.md) for more details.

The following is outdated.

---

Some initial thoughts on translation:

## Request a new translation

To request to add a new translation, the user needs to submit an issue at [translation-coordination](https://github.com/flaskcwg/translation-coordination) repo.

Then finish the following tasks:

- Generate a repository from [flaskcwg/translation-template](https://github.com/flaskcwg/translation-template), include all branches.
- Name your repository as `flask-docs-<lang code>`, for example, `flask-docs-es`.
- Setup ReadtheDocs to connect your repository, use `flask-<lang code>` as the subdomain, set the default version to the `main` branch and enable single version.
- Translate the README and the pull request template (optional).
- Update the title, clone URL, upstream URL, and folder name in the README. You can update the README to add more format or translate tips for your language.
- Translate the `docs/index.rst` file.
- Translate the `docs/foreword.rst` file.
- Translate the `docs/advanced-foreword.rst` file.
- Translate the `docs/installation.rst` file.
- Translate the `docs/quickstart.rst` file.
- Translate the "Tutorial" part of the docs.

When these tasks were finished, we switch the repo into flaskcwg.

When a translation is finished, we can add the link to Flask documentation and make the docs live in flask.palletsprojects.com.

The detailed instructions and tips can be found in the [issue template](https://github.com/flaskcwg/translation-coordination/issues/new?assignees=&labels=language&template=new-translation.md).

## Contributing

The details of contributing guide are covered in the README of the [translation-template repo](https://github.com/flaskcwg/translation-template).

In short, the README contains a list of all the chapters and files that need to be translated, a user needs to make the entry they want to translate with their username:

```
- [ ] example.rst @your_username Your Name
```

At last, the to-do list will become a credit list of all the translation contributors.

### Update from English docs/sources

- When pallets/flask has a merged PR labeled with `docs`, create a new issue (hope this could be done with a bot) in the translations-coordination repo. When all the translations finished the update, close the issue.

Feel free to leave your suggestions and ideas!

## Todo

- [x] A translation contributing guide.
- [x] Make a to-do list for all the chapters and sources.
- [x] Create a translation-coordination repo.
- [x] Create a translation template repo.

P.S. I will read through the related discussion in discord then update this.

**Comment by greyli** [comment]
I will take the [Chinese translation](https://github.com/greyli/flask-docs-zh) as a test of this workflow.

**Comment by greyli** [comment]
Now the translation is based on Sphinx and gettext, the [translation template repo](https://github.com/flaskcwg/translation-template), and [the instruction for language coordinator](https://github.com/flaskcwg/translation-coordination/blob/main/.github/ISSUE_TEMPLATE/new-translation.md) are updated.
